### ISSUE TITLE
Need to contact you about a deprecated plugin that I would like to modernize

### ISSUE THREAD

**Issue by DollarStoreCPU** [TRSoftware1/GambleBarVersion#1]
Couldn't find an email on your github page. I used to use [ConsoleInGame](https://www.spigotmc.org/resources/consoleingame-run-commands-through-console-from-in-game.10246/), a plugin developed by you that has since been removed from your GitHub. Would you be willing to re-publish or share the source code with me? I would love to make it compatible with newer versions of MC.

you can reach me via email if you need: kflynn42069@gmail.com

**Comment by TRSoftware1** [comment]
Hello, repo can be found here, feel free.
https://github.com/TRSoftware1/ConsoleInGame
